cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ozkurt:
      email: ozgun@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: "\xD6zg\xFCn Kurt"
      password: password123
    tayyardurden:
      email: tgorkemsayer@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: "Tayyar A\u011Fa"
      password: $2b$12$MiKxccOGfRwRNLZPxHBqjeQQuFiI4x9W4ZPSBuL95VDlHuornMe26
    tuncakar:
      email: tuna@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: "Tayyar A\u011Fa"
      password: password345
pre-authorized:
  emails:
    - tgorkemsayer@gmail.com
