cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 5
      logged_in: false
      name: John Smith
      password: $2b$12$o20Sq7Zd/y.JJ8q29GYjXe/4oBxo8skH1JfWVHUUJ4xq5evAkwehK
    okurt:
      email: tgorkemsayer@gmail.com
      failed_login_attempts: 21
      logged_in: false
      name: "\xD6zg\xFCn Kurt"
      password: $2b$12$exNjpu3V2wHjjZPAKS5k7eyjgpBNXfIlksIbrSlkPEp/S7L1gNoEW
pre-authorized:
  emails:
  - melsby@gmail.com
  - tgorkemsayer@gmail.com
