cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    okurt:
      email: seyfettin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: "\xD6zg\xFCn Kurt"
      password: $2b$12$L8a6.LY18BYoR75gNWUwDetCVVLDDQgI6OJRSoKulGCrii3oXMt2C
    tayyardurden:
      email: tgorkemsayer@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$MiKxccOGfRwRNLZPxHBqjeQQuFiI4x9W4ZPSBuL95VDlHuornMe26
pre-authorized:
  emails:
  - tgorkemsayer@gmail.com
